### ISSUE TITLE
reference values

### ISSUE THREAD

**Issue by nschloe** [konovalenko-iitp/proLab#1]
I'll try to add prolab to [colorio](https://github.com/nschloe/colorio). Do you have some reference values for the transformation for XYZ that I could use as a test?

**Comment by konovalenko-iitp** [comment]
Sorry that I did not reply for a while.
I suggest testing the code on the vertices of the sRGB gamut, considering D65 as a reference illuminant:

sRGB =
     0,     0,     0;
     1,     0,     0;
     0,     1,     0;
     0,     0,     1;
     0,     1,     1;
     1,     0,     1;
     1,     1,     0;
     1,     1,     1.

CIE XYZ =
         0,         0,         0;
    0.4125,    0.2127,    0.0193;
    0.3576,    0.7152,    0.1192;
    0.1804,    0.0722,    0.9503;
    0.5380,    0.7873,    1.0695;
    0.5929,    0.2848,    0.9696;
    0.7700,    0.9278,    0.1385;
    0.9505,    1.0000,    1.0888.

proLab =
         0,         0,         0;
   63.8813,   64.6958,   26.6611;
   93.2702,  -46.2794,   30.9420;
   67.8217,   19.0252,  -65.5766;
   96.5227,  -23.0585,   -9.5024;
   82.3994,   48.2089,  -32.2321;
   98.6665,  -10.1353,   34.9347;
  100.0000,   -0.0000,   -0.0000.

**Comment by nschloe** [comment]
Thanks for the reference values. Unfortunately, I'm getting something else. What you do for prolab is 
 * normalize xyz w.r.t. the D65 whitepoint
 * append 1
 * P * xyz with P
   ```
   79.4725 486.6610 153.7311 0
   649.9038 −595.4477 −20.4498 0
   50.8625 194.9377 −223.4334 0
   0.7947 3.8666 1.5373 1
   ```
  * Divide entries 1-3 by the entry 4

Correct? For `xyz1 = 0.4125, 0.2127, 0.0193` I'm getting (step-by-step)
 * `xyz100 =  41.25, 21.27, 1.93`
 * after normalization: `0.43399581, 0.2127,     0.01772545`
 * append 1: `0.43399581, 0.2127,     0.01772545, 1`
 * P * xyz+1 : `140.7284796  155.04132013  59.5769036 2.194571624123234`
 * divide by last entry: `64.12571732 70.64764641 27.14739539`

This is different from `63.8813, 64.6958, 26.6611`. Let me know where this is going wrong.

**Comment by konovalenko-iitp** [comment]
You should use matrix Q instead of P.
It is the Q matrix that is intended to be multiplied by the normalized XYZ coordinates.
This method is universal and preferable.
The P matrix is meant to be multiplied by the original XYZ coordinates and depends on the reference illuminant.
See details in Section "BASICS OF PROLAB COLOUR MODEL" of paper.

**Comment by nschloe** [comment]
I see, yes. 
```
ref:      [63.8813,    64.6958,    26.6611]
computed: [63.88359213 64.69862776 26.66672331]
```
which is still a little off. Note that I'm using the the standard D65 whitepoint https://en.wikipedia.org/wiki/Illuminant_D65#Definition, `X=95.047, Y=100, Z=108.883`. In your article you give `X=95.05, Y=100, Z=108.883`, perhaps that's worth a fix. Even with your approximate whitepoint, I'm not getting the correct values. Any idea why that may be?

**Comment by nschloe** [comment]
Even with the full-precision Q from https://github.com/konovalenko-iitp/proLab/blob/main/matlab/proLab_param.m I'm getting
```
[63.88402887 64.69906405 26.66690166]
```

**Comment by nschloe** [comment]
Even with the weird whitepoint https://github.com/konovalenko-iitp/proLab/blob/main/matlab/D65.m, I'm getting
```
[63.88402863 64.69906646 26.66690162]
```

**Comment by konovalenko-iitp** [comment]
That's my fault: I write rounded values CIE XYZ, while more accurate ones were used to calculate the proLab.
For the XYZ data that I sent you
proLab =
                   0                   0                   0
  63.884028628377536  64.699066463379509  26.666901623982760
  93.271656907410005 -46.280088804701613  30.942486748294701
  67.823197963285779  19.011255069252925 -65.573897146496236
  96.522178200629114 -23.057743401794138  -9.503680915678638
  82.397152928899970  48.219875687988292 -32.234075295144550
  98.666000272917827 -10.136686715198890  34.935595711535115
  99.999999821181234   0.002758532072690   0.001127802997320

This is in line with your last comment.

Thanks for the comments on D65.
I have fixed the function https://github.com/konovalenko-iitp/proLab/blob/main/matlab/D65.m and the text of the article.
The new result for the same XYZ data is as follows:
proLab =
                  0                  0                  0
   63.8840288724046   64.6990640516586   26.6669016620194
   93.2716571815066  -46.2800903959253   30.9424868459988
   67.8231981080096   19.0112542939369  -65.5738972992030
   96.5221783934792  -23.0577449276171   -9.5036807889233
   82.3971530943598   48.2198738004278  -32.2340753634712
   98.6660005066217  -10.1366890587630   34.9355957675890
   100.0000000000022   0.0027564564733    0.0011278893172

This is in line with your penultimate comment.

**Comment by nschloe** [comment]
Got it. To avoid uncertainty, I'd recommend using the same Q in the article and in the code. You can fix it to so many significant digits, too, even if you throw away a little bit of your optimization. It's more important that the scheme is reproducible. Let me know which Q is the official one in the end.

**Comment by konovalenko-iitp** [comment]
We are discussing this topic with coauthors.
I will answer you later.

**Comment by konovalenko-iitp** [comment]
The official matrix Q should be considered the new (!) matrix, which can be found at https://github.com/konovalenko-iitp/proLab/blob/main/matlab/proLab_param.m.
This matrix will be published later in the article.
Thank you for the recommendations!

**Comment by nschloe** [comment]
Good. I'd also recommend putting some reference values somewhere to give programmers some simple check if they did the right thing.

**Comment by konovalenko-iitp** [comment]
Done: https://github.com/konovalenko-iitp/proLab/blob/main/matlab/proLab_reference_values.m
